pid /tmp/dsh-proxy-nginx.pid;
error_log stderr info;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    client_body_temp_path /tmp/dsh-proxy-client-body;
    proxy_temp_path /tmp/dsh-proxy-proxy;
    fastcgi_temp_path /tmp/dsh-proxy-fastcgi;
    uwsgi_temp_path /tmp/dsh-proxy-uwsgi;
    scgi_temp_path /tmp/dsh-proxy-scgi;
    sendfile on;
    keepalive_timeout 65;
    include dsh-web.conf;
}
